api_platform:
    collection:
        pagination:
            items_per_page: 5 # Default value
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: Hello API Platform
    version: 1.0.0
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true


services:
    article.boolean_filter:
        parent: 'api_platform.doctrine.orm.boolean_filter'
        arguments: [ { enabled: ~ } ]
        tags: [ 'api_platform.filter' ]